[package]
name = "dollah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dollah"
path = "src/dollah.rs"

[[bin]]
name = "numba"
path = "src/numba.rs"